version: "2.2"
services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
      args:
        - ENV=development
      target: builder
    ports:
      - 8480:${APP_PORT}
    environment:
      AWS_HOST: http://minio:9000
      AWS_ACCESS_KEY_ID: &minio_user minio
      AWS_SECRET_ACCESS_KEY: &minio_pass minio123
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_HOST: db
      DB_PORT: 5432
      APP_PORT: ${APP_PORT}
      DATABASE_URL: "postgres://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}"
    volumes:
      - ./api/src:/app/src:ro
      - ./api/migrations:/app/migrations:ro
      - ./api/Cargo.toml:/app/Cargo.toml:ro
    command: cargo watch -x "run --target x86_64-unknown-linux-musl"
    links:
      - db

  ui:
    image: node:16
    ports:
      - 8000:8000
    environment:
      ENVIRONMENT_NAME: local-dev
    working_dir: /app
    command: ['node_modules/.bin/webpack', 'serve']
    links:
      - api
      - abbreviator
    volumes:
      - "./ui:/app:ro"

  minio:
    image: minio/minio:latest
    command: server /data --console-address :9001
    volumes:
      - miniodata:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_BROWSER: 'on'
      MINIO_ROOT_USER: *minio_user
      MINIO_ROOT_PASSWORD: *minio_pass

  abbreviator:
    image: camptocamp/abbreviator:main
    ports:
      - "8001:8080"
    environment:
      ID_LENGTH: 5
      DATABASE_URL: "sqlite::memory:"
      HOST_WHITELIST: "localhost"

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - ${DB_PORT}:5432
    # command: postgres -c log_statement=all for debugging

volumes:
  miniodata:
