version: "3"
services:
  api:
    init: true # handle kill signals for rust
    image: camptocamp/swissgeol_local_api:latest
    ports:
      - 8480:3000
    environment:
      AWS_HOST: http://minio:9000
      AWS_ACCESS_KEY_ID: &minio_user minio
      AWS_SECRET_ACCESS_KEY: &minio_pass minio123
      PGUSER: &db_user www-data
      PGPASSWORD: &db_pass www-data
      PGDATABASE: &db_name swissgeol-local
      PGHOST: db
      PGPORT: "5432"
      APP_PORT: "3000"
      SQLX_OFFLINE: "true"
      DATABASE_URL: "postgres://www-data:www-data@db:5432/swissgeol-local"
    command: ["cargo", "watch", "--poll", "--shell", "cargo run --offline --target x86_64-unknown-linux-musl"]
    volumes:
      - ./api/src:/app/src:ro
      - ./api/migrations:/app/migrations:ro
      - ./api/Cargo.toml:/app/Cargo.toml:ro
    links:
      - db

  ui:
    image: node:16
    ports:
      - 8000:8000
    environment:
      ENVIRONMENT_NAME: local-dev
    working_dir: /app
    command: ['node_modules/.bin/webpack', 'serve']
    links:
      - api
      - abbreviator
    volumes:
      - "./ui:/app:ro"

  minio:
    image: minio/minio:latest
    command: server /data --console-address :9001
    volumes:
      - miniodata:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_BROWSER: 'on'
      MINIO_ROOT_USER: *minio_user
      MINIO_ROOT_PASSWORD: *minio_pass

  abbreviator:
    image: camptocamp/abbreviator:latest
    ports:
      - "8001:8080"
    environment:
      ID_LENGTH: 5
      DATABASE_URL: "sqlite::memory:"
      HOST_WHITELIST: "localhost"

  db:
    image: camptocamp/postgres:11
    environment:
      POSTGRES_USER: *db_user
      POSTGRES_PASSWORD: *db_pass
      POSTGRES_DB: *db_name
    ports:
      - 15432:5432
    # command: postgres -c log_statement=all for debugging

volumes:
  miniodata:
