[package]
name = "api"
version = "0.1.1"
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

# Config
clap = { version = "3.2.20", features = ["derive", "env"]}
dotenv = "0.15.0"

# Web
axum = { version = "0.5.15", features = ["headers"] }
axum-macros = "0.2.3"
hyper = { version = "0.14.20", features = ["full"] }
tokio = { version = "1.21.0", features = ["full"] }
tower = "0.4.13"
tower-http = { version = "0.3.4", features = ["cors", "trace"] }

# Database
sqlx = { version = "0.6.1", features = ["runtime-tokio-rustls", "postgres", "offline", "uuid", "time"] }

# AWS
aws-config = "0.48.0"
aws-sdk-s3 = "0.18.0"

# Serialization
serde = {version = "1.0.144", features = ["derive"]}
serde_json = "1.0.85"

# Logging
tracing = "0.1.36"
tracing-subscriber = { version="0.3.15", features = ["env-filter"] }

# Errors
anyhow = "1.0.64"
thiserror = "1.0.34"

# Utils
chrono = { version = "0.4.22", features = ["serde"]}
once_cell = "1.14.0"
reqwest = { version = "0.11.11", default-features = false, features = ["rustls-tls", "hyper-rustls", "json"]}
url = "2.2.2"
uuid = { version = "1.1.2", features = ["serde", "v4"] }
jsonwebtoken = "8.1.1"
