[package]
name = "api"
version = "0.1.1"
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
axum = "0.4.5"
axum-macros = "0.1.0"
clap = { version = "3.0.14", features = ["derive", "env"]}
dotenv = "0.15.0"
hyper = { version = "0.14.16", features = ["full"] }
serde = {version = "1", features = ["derive"]}
serde_json = "1"
sqlx = { version = "0.5.10", features = ["runtime-tokio-rustls", "postgres", "offline", "uuid", "time"] }
tokio = { version = "1", features = ["full"] }
tower = "0.4.11"
tower-http = { version = "0.2.2", features = ["cors", "trace"] }
tracing = "0.1.30"
tracing-subscriber = { version="0.3.8", features = ["env-filter"] }
uuid = { version = "0.8.2", features = ["serde", "v4"] }
aws-config = "0.7.0"
aws-sdk-s3 = "0.7.0"
jsonwebtokens-cognito = "0.1.0-alpha"
jsonwebtokens = "1.1.0"
