[package]
name = "api"
version = "0.1.1"
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

# Config
clap = { version = "3.1.2", features = ["derive", "env"]}
dotenv = "0.15.0"

# Web
axum = { version = "0.4.8", features = ["headers"] }
axum-macros = "0.1.2"
hyper = { version = "0.14.17", features = ["full"] }
tokio = { version = "1.17.0", features = ["full"] }
tower = "0.4.12"
tower-http = { version = "0.2.3", features = ["cors", "trace"] }

# Database
sqlx = { version = "0.5.11", features = ["runtime-tokio-rustls", "postgres", "offline", "uuid", "time"] }

# AWS
aws-config = "0.8.0"
aws-sdk-s3 = "0.8.0"

# Serialization
serde = {version = "1.0.136", features = ["derive"]}
serde_json = "1.0.79"

# Logging
tracing = "0.1.31"
tracing-subscriber = { version="0.3.9", features = ["env-filter"] }

# Errors
anyhow = "1.0.55"
thiserror = "1.0.30"

# Utils
chrono = { version = "0.4.19", features = ["serde"]}
once_cell = "1.9.0"
reqwest = { version = "0.11.9", default-features = false, features = ["rustls-tls", "hyper-rustls", "json"]}
url = "2.2.2"
uuid = { version = "0.8.2", features = ["serde", "v4"] }
jsonwebtoken = "8.0.1"
